/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JButton;

/**
 *
 * @author Maurizio
 */
public class PrincipalV extends javax.swing.JFrame {

    /**
     * Creates new form principalView
     */
    public PrincipalV() {
        initComponents();
    }
    //<editor-fold defaultstate="collapsed" desc=" Getters ">

    public JButton getBtnAlumnos() {
        return btnAlumnos;
    }

    public JButton getBtnCarrera() {
        return btnCarrera;
    }

    public JButton getBtnCursado() {
        return btnCursado;
    }

    public JButton getBtnInscripcion() {
        return btnInscripcion;
    }

    public JButton getBtnMaterias() {
        return btnMaterias;
    }

    public JButton getBtnProfesores() {
        return btnProfesores;
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlumnos = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnCursado = new javax.swing.JButton();
        btnCarrera = new javax.swing.JButton();
        btnInscripcion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setBackground(new java.awt.Color(0, 0, 204));

        btnAlumnos.setBackground(new java.awt.Color(204, 153, 255));
        btnAlumnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAlumnos.setForeground(new java.awt.Color(153, 102, 255));
        btnAlumnos.setText("Alumnos");

        btnProfesores.setBackground(new java.awt.Color(204, 153, 255));
        btnProfesores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProfesores.setForeground(new java.awt.Color(153, 102, 255));
        btnProfesores.setText("Profesores");

        btnMaterias.setBackground(new java.awt.Color(204, 153, 255));
        btnMaterias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMaterias.setForeground(new java.awt.Color(153, 102, 255));
        btnMaterias.setText("Materias");

        btnCursado.setBackground(new java.awt.Color(204, 153, 255));
        btnCursado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCursado.setForeground(new java.awt.Color(153, 102, 255));
        btnCursado.setText("Cursado");

        btnCarrera.setBackground(new java.awt.Color(204, 153, 255));
        btnCarrera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCarrera.setForeground(new java.awt.Color(153, 102, 255));
        btnCarrera.setText("Carrera");

        btnInscripcion.setBackground(new java.awt.Color(204, 153, 255));
        btnInscripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInscripcion.setForeground(new java.awt.Color(153, 102, 255));
        btnInscripcion.setText("Inscripción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(btnCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCursado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlumnos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCursado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnCarrera;
    private javax.swing.JButton btnCursado;
    private javax.swing.JButton btnInscripcion;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnProfesores;
    // End of variables declaration//GEN-END:variables
}
